# Generated by Django 4.2.13 on 2024-06-01 11:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                default=1, max_length=2, verbose_name="Страна"
            ),
            preserve_default=False,
        ),
    ]
