# Generated by Django 5.0.4 on 2024-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_blogpost_options_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100, verbose_name="Название версии"),
        ),
    ]
