# Generated by Django 4.2.13 on 2024-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_version_version_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goods/", verbose_name="Изображение"
            ),
        ),
    ]
